In [2]:
#imports 
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, PolynomialFeatures
from sklearn.preprocessing import OrdinalEncoder , StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

In [3]:
tdf=pd.read_csv("data_center_hybrid.csv")
print(tdf.index)
print("All columns are")
ai=0
for i in tdf:
    print(ai,i)
    ai+=1

RangeIndex(start=0, stop=126770, step=1)
All columns are
0 Year
1 Facility_ID
2 Facility_Name
3 Owner_Company
4 City
5 Country
6 Facility_Type
7 Estimated_Capacity_MW
8 PUE
9 Cooling_System_Type
10 WUE_L_per_kWh
11 Daily_Electricity_Usage_MWh
12 Daily_Water_Usage_Gallons
13 Surrounding_Water_Stress_Tier

In [3]:
tdf.head(n=10)

,Year,Facility_ID,Facility_Name,Owner_Company,City,Country,Facility_Type,Estimated_Capacity_MW,PUE,Cooling_System_Type,WUE_L_per_kWh,Daily_Electricity_Usage_MWh,Daily_Water_Usage_Gallons,Surrounding_Water_Stress_Tier
0,2019,DC-D2763E00,NAP de las Americas Madrid,Terremark,Madrid,Spain,Enterprise/Standard,6.24,1.975,Evaporative,1.481,183.62,36362.94,Low
1,2020,DC-D2763E00,NAP de las Americas Madrid,Terremark,Madrid,Spain,Enterprise/Standard,6.36,1.967,Evaporative,1.459,254.34,49833.60,Low
2,2021,DC-D2763E00,NAP de las Americas Madrid,Terremark,Madrid,Spain,Enterprise/Standard,6.47,1.928,Evaporative,1.450,266.85,53026.35,Low
3,2022,DC-D2763E00,NAP de las Americas Madrid,Terremark,Madrid,Spain,Enterprise/Standard,6.59,1.897,Evaporative,1.413,199.14,39198.30,Low
4,2023,DC-D2763E00,NAP de las Americas Madrid,Terremark,Madrid,Spain,Enterprise/Standard,6.70,1.869,Evaporative,1.389,225.94,44366.48,Low
5,2024,DC-D2763E00,NAP de las Americas Madrid,Terremark,Madrid,Spain,Enterprise/Standard,6.82,1.842,Evaporative,1.369,195.72,38435.64,Low
6,2025,DC-D2763E00,NAP de las Americas Madrid,Terremark,Madrid,Spain,Enterprise/Standard,6.95,1.815,Evaporative,1.341,229.83,44852.92,Low
7,2019,DC-97AB1D99,Central Office 2,StarHub Ltd.,Singapore,Singapore,Enterprise/Standard,8.20,1.796,Air Cooled,0.093,329.47,4488.46,Low
8,2020,DC-97AB1D99,Central Office 2,StarHub Ltd.,Singapore,Singapore,Enterprise/Standard,8.35,1.792,Air Cooled,0.092,253.65,3430.72,Low
9,2021,DC-97AB1D99,Central Office 2,StarHub Ltd.,Singapore,Singapore,Enterprise/Standard,8.50,1.759,Air Cooled,0.091,270.58,3679.70,Low

In [4]:
tdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126770 entries, 0 to 126769
Data columns (total 14 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Year                           126770 non-null  int64
 1   Facility_ID                    126770 non-null  object
 2   Facility_Name                  126770 non-null  object
 3   Owner_Company                  126770 non-null  object
 4   City                           126770 non-null  object
 5   Country                        126770 non-null  object
 6   Facility_Type                  126770 non-null  object
 7   Estimated_Capacity_MW          126770 non-null  float64
 8   PUE                            126770 non-null  float64
 9   Cooling_System_Type            126770 non-null  object
 10  WUE_L_per_kWh                  126770 non-null  float64
 11  Daily_Electricity_Usage_MWh    126770 non-null  float64
 12  Daily_Water_Usage_Gallons      126770 non-null  float64
 13  Surrounding_Water_Stress_Tier  126770 non-null  object
dtypes: float64(5), int64(1), object(8)
memory usage: 13.5+ MB

In [5]:
for col in tdf.select_dtypes(include=['object', 'category']):
    print(tdf[col].value_counts())
    print("-" * 20)  # Separator line

Facility_ID
DC-D2763E00    7
DC-21C0EA0D    7
DC-518B7F4C    7
DC-6D0E9079    7
DC-B0E5037A    7
              ..
DC-1C259F9E    7
DC-3CAF05F5    7
DC-232F02F1    7
DC-B2E3F8DD    7
DC-31D8B15E    7
Name: count, Length: 18110, dtype: int64
--------------------
Facility_Name
Amsterdam                     231
Singapore                     217
London                        189
Sydney                        161
Frankfurt                     154
                             ...
Northland Utica Datacenter      7
SS&C GlobeOp Data Center        7
Hivelocity - Seattle 1          7
2020 5th Avenue (SEA11)         7
ICS_DataCenter_216              7
Name: count, Length: 16286, dtype: int64
--------------------
Owner_Company
Amazon AWS                                               3731
Equinix                                                  3374
Lumen                                                    2821
China Telecom                                            2212
Zenlayer                                                 2163
                                                         ...
Oman Data Park                                              7
Behringer Harvard                                           7
Wilcon                                                      7
Ngoya ETIX DC (Ghana) Limited ( trading as " ONIX")         7
ICS BİLİŞİM TEKNOLOJİLERİ DANIŞMANLIK HİZMETLERİ A.Ş.       7
Name: count, Length: 4180, dtype: int64
--------------------
City
Unknown             61418
States               1281
Ashburn               938
Sterling              847
Manassas              700
                    ...
Laguna                  7
Garenne-Colombes        7
Colombes                7
Aravaca                 7
Winfield                7
Name: count, Length: 2513, dtype: int64
--------------------
Country
United States     61726
United Kingdom     5229
Germany            4088
France             3906
China              3836
                  ...
100015                7
100016                7
200083                7
213311                7
Cabo Verde            7
Name: count, Length: 344, dtype: int64
--------------------
Facility_Type
Enterprise/Standard    105189
Colocation              12516
Hyperscale/AI            9065
Name: count, dtype: int64
--------------------
Cooling_System_Type
Air Cooled       79541
Evaporative      45612
Liquid Cooled     1617
Name: count, dtype: int64
--------------------
Surrounding_Water_Stress_Tier
Medium    46718
High      45234
Low       34818
Name: count, dtype: int64
--------------------

In [6]:
tdf.columns

Index(['Year', 'Facility_ID', 'Facility_Name', 'Owner_Company', 'City',
       'Country', 'Facility_Type', 'Estimated_Capacity_MW', 'PUE',
       'Cooling_System_Type', 'WUE_L_per_kWh', 'Daily_Electricity_Usage_MWh',
       'Daily_Water_Usage_Gallons', 'Surrounding_Water_Stress_Tier'],
      dtype='object')

In [4]:
# Data Cleaning
df = tdf
df = df.drop(columns=['Facility_ID', 'Facility_Name', 'Owner_Company', 'City','Country'])

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126770 entries, 0 to 126769
Data columns (total 9 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Year                           126770 non-null  int64
 1   Facility_Type                  126770 non-null  object
 2   Estimated_Capacity_MW          126770 non-null  float64
 3   PUE                            126770 non-null  float64
 4   Cooling_System_Type            126770 non-null  object
 5   WUE_L_per_kWh                  126770 non-null  float64
 6   Daily_Electricity_Usage_MWh    126770 non-null  float64
 7   Daily_Water_Usage_Gallons      126770 non-null  float64
 8   Surrounding_Water_Stress_Tier  126770 non-null  object
dtypes: float64(5), int64(1), object(3)
memory usage: 8.7+ MB

In [9]:
df.head()

,Year,Facility_Type,Estimated_Capacity_MW,PUE,Cooling_System_Type,WUE_L_per_kWh,Daily_Electricity_Usage_MWh,Daily_Water_Usage_Gallons,Surrounding_Water_Stress_Tier
0,2019,Enterprise/Standard,6.24,1.975,Evaporative,1.481,183.62,36362.94,Low
1,2020,Enterprise/Standard,6.36,1.967,Evaporative,1.459,254.34,49833.60,Low
2,2021,Enterprise/Standard,6.47,1.928,Evaporative,1.450,266.85,53026.35,Low
3,2022,Enterprise/Standard,6.59,1.897,Evaporative,1.413,199.14,39198.30,Low
4,2023,Enterprise/Standard,6.70,1.869,Evaporative,1.389,225.94,44366.48,Low

In [10]:
le = LabelEncoder()
df['Surrounding_Water_Stress_Tier'] = le.fit_transform(df['Surrounding_Water_Stress_Tier'])
print(df['Surrounding_Water_Stress_Tier'])

0         1
1         1
2         1
3         1
4         1
         ..
126765    0
126766    0
126767    0
126768    0
126769    0
Name: Surrounding_Water_Stress_Tier, Length: 126770, dtype: int64

In [11]:
X = df.drop(['Surrounding_Water_Stress_Tier'],axis = 1)
y = df['Surrounding_Water_Stress_Tier']
print(X.columns)
print(y)

Index(['Year', 'Facility_Type', 'Estimated_Capacity_MW', 'PUE',
       'Cooling_System_Type', 'WUE_L_per_kWh', 'Daily_Electricity_Usage_MWh',
       'Daily_Water_Usage_Gallons'],
      dtype='object')
0         1
1         1
2         1
3         1
4         1
         ..
126765    0
126766    0
126767    0
126768    0
126769    0
Name: Surrounding_Water_Stress_Tier, Length: 126770, dtype: int64

In [12]:
# Direct without category
X = df.drop(['Surrounding_Water_Stress_Tier'],axis = 1)
y = df['Surrounding_Water_Stress_Tier']
X = X.drop(columns=['Facility_Type','Cooling_System_Type'])


Xtrain, Xtest, ytrain, ytest = train_test_split(X,y,test_size=0.2,random_state=42)


model = Pipeline([
    ("scaler", StandardScaler()),
    ("regressor", LogisticRegression())
])


model.fit(Xtrain, ytrain)


ypred = model.predict(Xtest)


print("Accuracy Score:", accuracy_score(ytest, ypred))

Accuracy Score: 0.370592411453814

In [13]:
scores = cross_val_score(model,X,y,cv=10,scoring="accuracy")
print("Accuracy:", scores)
print("Mean accuracy:", scores.mean())

Accuracy: [0.37161789 0.36641161 0.36798927 0.36909363 0.36467619 0.36956693
 0.36933028 0.3743788  0.36128422 0.36735821]
Mean accuracy: 0.3681707028476769

In [14]:
print(X.columns)

Index(['Year', 'Estimated_Capacity_MW', 'PUE', 'WUE_L_per_kWh',
       'Daily_Electricity_Usage_MWh', 'Daily_Water_Usage_Gallons'],
      dtype='object')

In [15]:
print(tdf['City'])

0          Madrid
1          Madrid
2          Madrid
3          Madrid
4          Madrid
           ...
126765    Unknown
126766    Unknown
126767    Unknown
126768    Unknown
126769    Unknown
Name: City, Length: 126770, dtype: object

In [5]:
# let's try to includde other columns
df = pd.read_csv("data_center_hybrid.csv")

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126770 entries, 0 to 126769
Data columns (total 14 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Year                           126770 non-null  int64
 1   Facility_ID                    126770 non-null  object
 2   Facility_Name                  126770 non-null  object
 3   Owner_Company                  126770 non-null  object
 4   City                           126770 non-null  object
 5   Country                        126770 non-null  object
 6   Facility_Type                  126770 non-null  object
 7   Estimated_Capacity_MW          126770 non-null  float64
 8   PUE                            126770 non-null  float64
 9   Cooling_System_Type            126770 non-null  object
 10  WUE_L_per_kWh                  126770 non-null  float64
 11  Daily_Electricity_Usage_MWh    126770 non-null  float64
 12  Daily_Water_Usage_Gallons      126770 non-null  float64
 13  Surrounding_Water_Stress_Tier  126770 non-null  object
dtypes: float64(5), int64(1), object(8)
memory usage: 13.5+ MB

In [6]:
# Data Cleaning
df = df.drop(columns=['Facility_ID', 'Facility_Name'])

In [7]:
df.columns

Index(['Year', 'Owner_Company', 'City', 'Country', 'Facility_Type',
       'Estimated_Capacity_MW', 'PUE', 'Cooling_System_Type', 'WUE_L_per_kWh',
       'Daily_Electricity_Usage_MWh', 'Daily_Water_Usage_Gallons',
       'Surrounding_Water_Stress_Tier'],
      dtype='object')

In [8]:
le = LabelEncoder()
df['Surrounding_Water_Stress_Tier'] = le.fit_transform(df['Surrounding_Water_Stress_Tier'])
print(df['Surrounding_Water_Stress_Tier'])

0         1
1         1
2         1
3         1
4         1
         ..
126765    0
126766    0
126767    0
126768    0
126769    0
Name: Surrounding_Water_Stress_Tier, Length: 126770, dtype: int64

In [9]:
n = df.select_dtypes(include=['number']).columns.tolist()

non = df.select_dtypes(exclude=['number']).columns.tolist()

print(n)
print(non)

['Year', 'Estimated_Capacity_MW', 'PUE', 'WUE_L_per_kWh', 'Daily_Electricity_Usage_MWh', 'Daily_Water_Usage_Gallons', 'Surrounding_Water_Stress_Tier']
['Owner_Company', 'City', 'Country', 'Facility_Type', 'Cooling_System_Type']

In [80]:
df=pd.read_csv("data_center_hybrid.csv")

df = df.drop(columns=['Facility_ID', 'Facility_Name'])
X = df.drop("Surrounding_Water_Stress_Tier", axis=1)
y = df["Surrounding_Water_Stress_Tier"]


Xtrain, Xtest, ytrain, ytest = train_test_split(
    X, y, test_size=0.2)


numeric_cols = [
    "Year",
    "Estimated_Capacity_MW",
    "PUE",
    "WUE_L_per_kWh",
    "Daily_Electricity_Usage_MWh",
    "Daily_Water_Usage_Gallons"
]

categorical_cols = [
    "Owner_Company",
    "City",
    "Country",
    "Facility_Type",
    "Cooling_System_Type"
]


preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numeric_cols),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols)
    ]
)


model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", LogisticRegression(max_iter=1000))
])


model.fit(Xtrain, ytrain)


ypred = model.predict(Xtest)

print("Accuracy:", accuracy_score(ytest, ypred))

from sklearn.model_selection import cross_val_score

scores = cross_val_score(model, X, y, cv=5, scoring="accuracy")
print(scores)
print("Mean accuracy:", scores.mean())

Accuracy: 0.6290526149719965
[0.36329573 0.32180327 0.35146328 0.33391181 0.30224028]
Mean accuracy: 0.33454287291946044

In [83]:
# let's do some data cleaning
print(df["Owner_Company"].value_counts())
for i in (df["Owner_Company"].value_counts()):
    print(i,end=' ')

Owner_Company
Amazon AWS                                               3731
Equinix                                                  3374
Lumen                                                    2821
China Telecom                                            2212
Zenlayer                                                 2163
                                                         ...
Oman Data Park                                              7
Behringer Harvard                                           7
Wilcon                                                      7
Ngoya ETIX DC (Ghana) Limited ( trading as " ONIX")         7
ICS BİLİŞİM TEKNOLOJİLERİ DANIŞMANLIK HİZMETLERİ A.Ş.       7
Name: count, Length: 4180, dtype: int64
3731 3374 2821 2212 2163 2093 1519 1435 1316 1148 1120 1050 854 840 784 777 770 714 700 665 644 630 616 609 602 602 581 574 567 525 518 518 504 497 476 476 469 455 455 448 434 427 420 420 413 399 399 385 385 364 357 343 336 329 322 315 315 308 308 308 308 301 301 287 287 280 280 280 280 273 266 259 252 252 245 245 245 238 238 231 231 224 217 217 217 217 210 210 203 196 196 189 189 182 182 182 182 182 182 182 182 182 175 175 175 175 168 168 168 168 161 154 154 154 147 147 147 147 147 147 147 147 147 140 140 140 140 133 133 133 133 133 133 133 133 133 133 133 133 126 126 126 126 126 126 126 126 126 126 126 126 119 119 119 119 119 119 119 119 119 119 119 112 112 112 112 112 112 112 105 105 105 105 105 105 105 105 105 105 105 105 105 105 98 98 98 98 98 98 98 98 98 98 98 98 91 91 91 91 91 91 91 91 91 91 84 84 84 84 84 84 84 84 84 84 84 84 84 84 84 84 84 84 84 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7

In [84]:
print(df["Country"].value_counts())
for i in (df["Country"].value_counts()):
    print(i,end=' ')

Country
United States     61726
United Kingdom     5229
Germany            4088
France             3906
China              3836
                  ...
100015                7
100016                7
200083                7
213311                7
Cabo Verde            7
Name: count, Length: 344, dtype: int64
61726 5229 4088 3906 3836 3108 2905 2772 2394 2296 2086 1750 1652 1547 1351 1225 1015 945 924 910 903 882 875 861 763 693 665 588 567 504 497 462 455 448 434 364 350 350 343 336 336 329 322 287 266 252 231 210 203 203 189 189 189 182 175 154 147 133 133 126 119 119 112 112 105 105 105 98 98 98 91 91 84 84 84 77 77 77 63 63 63 63 63 56 56 56 49 49 49 49 49 49 49 42 42 42 42 42 42 42 35 35 35 35 35 35 28 28 28 28 28 28 28 28 28 28 28 28 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7

In [85]:
print(df["City"].value_counts())
for i in (df["City"].value_counts()):
    print(i,end=' ')

City
Unknown             61418
States               1281
Ashburn               938
Sterling              847
Manassas              700
                    ...
Laguna                  7
Garenne-Colombes        7
Colombes                7
Aravaca                 7
Winfield                7
Name: count, Length: 2513, dtype: int64
61418 1281 938 847 700 644 518 497 497 483 469 455 448 427 420 378 378 371 357 350 301 287 273 273 273 259 259 259 252 252 245 238 238 224 224 217 210 203 203 196 196 196 196 196 189 189 189 189 189 182 182 182 182 175 175 175 168 168 168 168 161 161 161 161 161 161 161 161 154 154 154 154 154 154 147 147 147 147 147 140 140 133 133 133 133 133 126 126 126 126 126 126 119 119 119 119 119 119 119 119 119 119 119 119 119 112 112 112 112 112 112 112 112 112 112 105 105 105 105 105 105 105 105 98 98 98 98 98 98 98 98 91 91 91 91 91 84 84 84 84 84 84 84 84 84 84 84 84 84 84 84 84 84 84 84 84 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 63 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 56 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 42 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 35 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 21 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7

In [86]:
# Grouping less than7 number categories to "other"

a = "Owner_Company"
counts = df[a].value_counts()

rarecategories = counts[counts < 8].index

df[a] = df[a].replace(rarecategories, 'Other')

print(df[a].value_counts())
print()
print()


a = "Country"
counts = df[a].value_counts()

rarecategories = counts[counts < 8].index

df[a] = df[a].replace(rarecategories, 'Other')

print(df[a].value_counts())
print()
print()


a = "City"
counts = df[a].value_counts()

rarecategories = counts[counts < 8].index

df[a] = df[a].replace(rarecategories, 'Other')

print(df[a].value_counts())
print()
print()

Owner_Company
Other                            17395
Amazon AWS                        3731
Equinix                           3374
Lumen                             2821
China Telecom                     2212
                                 ...
Riyadh Municipality                 14
Rockan Data Center AB               14
RockyNet Inc.                       14
Mauritius Telecom                   14
teknotel telekomunikasyon a s       14
Name: count, Length: 1696, dtype: int64


Country
United States            61726
United Kingdom            5229
Germany                   4088
France                    3906
China                     3836
                         ...
065014                      14
Guinea                      14
Madagascar                  14
Togo                        14
Serbia and Montenegro       14
Name: count, Length: 174, dtype: int64


City
Unknown            61418
Other              10066
States              1281
Ashburn              938
Sterling             847
                   ...
Kazan                 14
Joseph                14
+81-3-3454-1111       14
Järfälla              14
Kaiserslautern        14
Name: count, Length: 1076, dtype: int64

In [87]:
X = df.drop("Surrounding_Water_Stress_Tier", axis=1)
y = df["Surrounding_Water_Stress_Tier"]


Xtrain, Xtest, ytrain, ytest = train_test_split(
    X, y, test_size=0.2, random_state=42
)


numeric_cols = [
    "Year",
    "Estimated_Capacity_MW",
    "PUE",
    "WUE_L_per_kWh",
    "Daily_Electricity_Usage_MWh",
    "Daily_Water_Usage_Gallons"
]

categorical_cols = [
    "Owner_Company",
    "City",
    "Country",
    "Facility_Type",
    "Cooling_System_Type"
]


preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numeric_cols),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols)
    ]
)


model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", LogisticRegression(max_iter=1000))
])


model.fit(Xtrain, ytrain)


ypred = model.predict(Xtest)

print("Accuracy:", accuracy_score(ytest, ypred))

from sklearn.model_selection import cross_val_score

scores = cross_val_score(model, X, y, cv=5, scoring="accuracy")
print(scores)
print("Mean accuracy:", scores.mean())

Accuracy: 0.50903210538771
[0.35749783 0.32073835 0.35375089 0.3436933  0.31131182]
Mean accuracy: 0.3373984381162735

In [89]:
print('''Its better if we are leaving everything as it is .The performance is more in this way
But the performance is not good enough for the Voting Ensemble
We need to try other algorithms''')

Its better if we are leaving everything as it is .The performance is more in this way
But the performance is not good enough for the Voting Ensemble
We need to try other algorithms